theme: 

title: Your awesome title
email: sdfad@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Changed. Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: asdfa
github_username:  asdf

# fix bug "Error: No repo name found."
# https://github.com/jekyll/jekyll/issues/4705
repository: rigosk/rigosk.github.io



# Custom add ons

#google_analytics: 

# Build settings
markdown: kramdown
#theme: jekyll-theme-cayman-blog
gems:
  - jekyll-feed
